/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.submu.pug.application;

/**
 *
 * @author MW
 */
public class LauncherPanel extends javax.swing.JPanel {
    /**
     * Command to run when the editor button is pressed.
     */
    private LauncherCallback editorActionCommand;

    /**
     * Command to run when the game button is pressed.
     */
    private LauncherCallback gameActionCommand;

    /**
     * Creates new form LauncherPanel
     */
    public LauncherPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        gameButton = new javax.swing.JButton();
        editorButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Game Launcher");
        jLabel1.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 15, 0);
        add(jLabel1, gridBagConstraints);

        gameButton.setText("Game");
        gameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(gameButton, gridBagConstraints);

        editorButton.setText("Editor");
        editorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        add(editorButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Run the game button command when pressed.
     * @param evt the action event.
     */
    private void gameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameButtonActionPerformed
        gameActionCommand.execute();
    }//GEN-LAST:event_gameButtonActionPerformed

    /**
     * Run the editor button command when pressed.
     * @param evt the action event.
     */
    private void editorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorButtonActionPerformed
        editorActionCommand.execute();
    }//GEN-LAST:event_editorButtonActionPerformed

    /**
     * Sets the action command for the editor.
     * @param command the command to set.
     */
    public void setEditorActionCommand(LauncherCallback command) {
        editorActionCommand = command;
    }

    /**
     * Sets the action command for the game button.
     * @param gameActionCommand the command to set.
     */
    public void setGameActionCommand(LauncherCallback gameActionCommand) {
        this.gameActionCommand = gameActionCommand;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editorButton;
    private javax.swing.JButton gameButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
